#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env"
PRIVOXY_CONFIG="${PROJECT_DIR}/privoxy/config"
SYSTEMD_TEMPLATE="${PROJECT_DIR}/init/vps-proxy-stack.service"
SYSTEMD_TARGET="/etc/systemd/system/vps-proxy-stack.service"
CRON_TAG="# VPS_BLACKLIST_UPDATE"

if [[ ! -f "${ENV_FILE}" ]]; then
  cp "${PROJECT_DIR}/.env.example" "${ENV_FILE}"
  echo "Creato ${ENV_FILE} da .env.example"
fi

set -a
source "${ENV_FILE}"
set +a

mkdir -p "${PROJECT_DIR}/logs"
mkdir -p "${PROJECT_DIR}/privoxy"

PRIVOXY_LISTEN_IP="${PRIVOXY_LISTEN_IP:-127.0.0.1}"
PRIVOXY_LISTEN_PORT="${PRIVOXY_LISTEN_PORT:-8118}"
TOR_SOCKS_HOST="${TOR_SOCKS_HOST:-127.0.0.1}"
TOR_SOCKS_PORT="${TOR_SOCKS_PORT:-9050}"
PRIVOXY_SOCKET_TIMEOUT="${PRIVOXY_SOCKET_TIMEOUT:-300}"
PRIVOXY_FORWARDED_CONNECT_RETRIES="${PRIVOXY_FORWARDED_CONNECT_RETRIES:-1}"
PRIVOXY_MAX_CLIENT_CONNECTIONS="${PRIVOXY_MAX_CLIENT_CONNECTIONS:-1024}"
PRIVOXY_KEEP_ALIVE_TIMEOUT="${PRIVOXY_KEEP_ALIVE_TIMEOUT:-5}"
PRIVOXY_TOLERATE_PIPELINING="${PRIVOXY_TOLERATE_PIPELINING:-1}"

cat > "${PRIVOXY_CONFIG}" <<EOF
# ===========================================================================
#  Generated by init/bootstrap.sh
# ===========================================================================
listen-address  ${PRIVOXY_LISTEN_IP}:${PRIVOXY_LISTEN_PORT}
forward-socks5t   /   ${TOR_SOCKS_HOST}:${TOR_SOCKS_PORT}   .
socket-timeout          ${PRIVOXY_SOCKET_TIMEOUT}
forwarded-connect-retries ${PRIVOXY_FORWARDED_CONNECT_RETRIES}
max-client-connections  ${PRIVOXY_MAX_CLIENT_CONNECTIONS}
keep-alive-timeout ${PRIVOXY_KEEP_ALIVE_TIMEOUT}
tolerate-pipelining ${PRIVOXY_TOLERATE_PIPELINING}
EOF

echo "Privoxy config generata in ${PRIVOXY_CONFIG}"

docker compose -f "${PROJECT_DIR}/docker-compose.yml" up -d --build

echo "Stack avviato (unbound, tor, privoxy, mitmproxy)"

if [[ "${INSTALL_SYSTEMD:-1}" == "1" ]]; then
  tmp_service="$(mktemp)"
  trap 'rm -f "$tmp_service"' EXIT
  sed "s#{{PROJECT_DIR}}#${PROJECT_DIR}#g" "${SYSTEMD_TEMPLATE}" > "${tmp_service}"
  sudo install -m 0644 "${tmp_service}" "${SYSTEMD_TARGET}"
  sudo systemctl daemon-reload
  sudo systemctl enable --now vps-proxy-stack.service
  echo "Systemd service installato e abilitato: vps-proxy-stack.service"
fi

if [[ "${INSTALL_CRON:-1}" == "1" ]]; then
  CRON_SCHEDULE="${BLACKLIST_CRON_SCHEDULE:-0 */6 * * *}"
  CRON_CMD="cd ${PROJECT_DIR} && /usr/bin/docker compose run --rm --no-deps mitmproxy bash cron/update_blacklist.sh >> ${PROJECT_DIR}/logs/blacklist-cron.log 2>&1"

  current_cron="$(crontab -l 2>/dev/null || true)"
  filtered_cron="$(printf '%s\n' "${current_cron}" | grep -v "${CRON_TAG}" || true)"
  {
    printf '%s\n' "${filtered_cron}"
    printf '%s %s %s\n' "${CRON_SCHEDULE}" "${CRON_CMD}" "${CRON_TAG}"
  } | crontab -

  echo "Cron blacklist aggiornato: ${CRON_SCHEDULE}"
fi

echo "Bootstrap completato."
