#!/usr/bin/env bash
set -euo pipefail

BLACKLIST_URL="${BLACKLIST_URL:-https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts}"
OUTPUT_FILE="${OUTPUT_FILE:-/app/unbound/blacklist.conf}"

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

curl -fsSL "$BLACKLIST_URL" | awk '
BEGIN {
  print "# Auto-generated by update_blacklist.sh"
}
/^0\.0\.0\.0[[:space:]]+/ {
  domain=$2
  if (domain != "" && domain !~ /^#/) {
    print "local-zone: \"" domain "\" always_nxdomain"
  }
}
' > "$tmp_file"

install -m 0644 "$tmp_file" "$OUTPUT_FILE"
echo "Blacklist aggiornata: $OUTPUT_FILE"