#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # = repo/vpn/
REPO_ROOT="$(cd "${PROJECT_DIR}/.." && pwd)"                     # = repo root
ENV_FILE="${REPO_ROOT}/.env"
PRIVOXY_CONFIG="${PROJECT_DIR}/privoxy/config"
SYSTEMD_TEMPLATE="${PROJECT_DIR}/init/vps-proxy-stack.service"
SYSTEMD_TARGET="/etc/systemd/system/vps-proxy-stack.service"
CRON_TAG="# VPS_BLACKLIST_UPDATE"

UNBOUND_CONF_SRC="${PROJECT_DIR}/unbound/unbound.conf"
SSL_DIR="${PROJECT_DIR}/ssl-certificates"

if [[ ! -f "${ENV_FILE}" ]]; then
  cp "${REPO_ROOT}/.env.example" "${ENV_FILE}"
  echo "Created ${ENV_FILE} from .env.example"
fi

set -a
source "${ENV_FILE}"
set +a

mkdir -p "${PROJECT_DIR}/logs"
mkdir -p "${PROJECT_DIR}/privoxy"
mkdir -p "${SSL_DIR}"

PRIVOXY_LISTEN_IP="${PRIVOXY_LISTEN_IP:-0.0.0.0}"
PRIVOXY_LISTEN_PORT="${PRIVOXY_LISTEN_PORT:-8118}"
TOR_SOCKS_HOST="${TOR_SOCKS_HOST:-127.0.0.1}"
TOR_SOCKS_PORT="${TOR_SOCKS_PORT:-9050}"
PRIVOXY_SOCKET_TIMEOUT="${PRIVOXY_SOCKET_TIMEOUT:-300}"
PRIVOXY_FORWARDED_CONNECT_RETRIES="${PRIVOXY_FORWARDED_CONNECT_RETRIES:-1}"
PRIVOXY_MAX_CLIENT_CONNECTIONS="${PRIVOXY_MAX_CLIENT_CONNECTIONS:-1024}"
PRIVOXY_KEEP_ALIVE_TIMEOUT="${PRIVOXY_KEEP_ALIVE_TIMEOUT:-5}"
PRIVOXY_TOLERATE_PIPELINING="${PRIVOXY_TOLERATE_PIPELINING:-1}"

cat > "${PRIVOXY_CONFIG}" <<EOF
# ===========================================================================
#  Generated by init/bootstrap.sh
# ===========================================================================
listen-address  ${PRIVOXY_LISTEN_IP}:${PRIVOXY_LISTEN_PORT}
forward-socks5t   /   ${TOR_SOCKS_HOST}:${TOR_SOCKS_PORT}   .
socket-timeout          ${PRIVOXY_SOCKET_TIMEOUT}
forwarded-connect-retries ${PRIVOXY_FORWARDED_CONNECT_RETRIES}
max-client-connections  ${PRIVOXY_MAX_CLIENT_CONNECTIONS}
keep-alive-timeout ${PRIVOXY_KEEP_ALIVE_TIMEOUT}
tolerate-pipelining ${PRIVOXY_TOLERATE_PIPELINING}
EOF

echo "Privoxy config generated at ${PRIVOXY_CONFIG}"

# ---------------------------------------------------------------------------
# Generate TLS certificates if missing
# ---------------------------------------------------------------------------
if [[ ! -f "${SSL_DIR}/server.key" || ! -f "${SSL_DIR}/server.crt" ]]; then
  echo "TLS certificates not found; generating with TLS_MODE=${TLS_MODE:-selfsigned}..."
  bash "${SCRIPT_DIR}/generate-certs.sh"
fi

# ---------------------------------------------------------------------------
# Render unbound.conf - replace TLS placeholders
# ---------------------------------------------------------------------------
TLS_SERVICE_KEY="/etc/nginx/ssl-certificates/server.key"
TLS_SERVICE_PEM="/etc/nginx/ssl-certificates/server.crt"

if grep -q '{{TLS_SERVICE_KEY}}' "${UNBOUND_CONF_SRC}" 2>/dev/null; then
  sed -i "s|{{TLS_SERVICE_KEY}}|${TLS_SERVICE_KEY}|g" "${UNBOUND_CONF_SRC}"
  sed -i "s|{{TLS_SERVICE_PEM}}|${TLS_SERVICE_PEM}|g" "${UNBOUND_CONF_SRC}"
  echo "Unbound config: TLS paths updated."
fi

# ---------------------------------------------------------------------------
# Render tor/torrc from template
# Idempotent: always regenerates torrc from the template on every bootstrap run.
# Edit .env (TOR_EXIT_NODES, TOR_EXCLUDE_NODES) — never edit torrc directly.
# ---------------------------------------------------------------------------
TORRC_TEMPLATE="${PROJECT_DIR}/tor/torrc.template"
TORRC_OUTPUT="${PROJECT_DIR}/tor/torrc"

if [[ -f "${TORRC_TEMPLATE}" ]]; then
  cp "${TORRC_TEMPLATE}" "${TORRC_OUTPUT}"

  EXIT_NODES="${TOR_EXIT_NODES:-{de},{it},{ad},{mc},{al},{mm},{mv},{vn},{uz}}"
  EXCLUDE_NODES="${TOR_EXCLUDE_NODES:-{ch},{us},{gb},{au},{ca},{fr},{nl},{be},{ie},{se},{no},{dk},{fi},{jp},{kr},{cn},{ru}}"

  sed -i "s|{{EXIT_NODES}}|${EXIT_NODES}|g"       "${TORRC_OUTPUT}"
  sed -i "s|{{EXCLUDE_NODES}}|${EXCLUDE_NODES}|g" "${TORRC_OUTPUT}"

  if [[ "${TOR_CONTROL_ENABLED:-0}" == "1" ]]; then
    CONTROL_BLOCK="ControlPort ${TOR_CONTROL_PORT:-9051}"$'\n'"CookieAuthentication 1"
    # Use a Python one-liner to handle the multi-line substitution portably
    python3 -c "
import pathlib, sys
p = pathlib.Path('${TORRC_OUTPUT}')
p.write_text(p.read_text().replace('{{TOR_CONTROL_BLOCK}}', '''${CONTROL_BLOCK}'''))
"
  else
    sed -i "s|{{TOR_CONTROL_BLOCK}}||g" "${TORRC_OUTPUT}"
  fi

  echo "tor/torrc rendered (ExitNodes=${EXIT_NODES}, ControlPort=${TOR_CONTROL_ENABLED:-0})"
else
  echo "WARNING: tor/torrc.template not found — using existing torrc as-is"
fi

docker compose -f "${PROJECT_DIR}/docker-compose.yml" up -d --build

echo "Stack started (unbound, tor, privoxy, mitmproxy)"

if [[ "${INSTALL_SYSTEMD:-1}" == "1" ]]; then
  tmp_service="$(mktemp)"
  trap 'rm -f "$tmp_service"' EXIT
  sed "s#{{PROJECT_DIR}}#${PROJECT_DIR}#g" "${SYSTEMD_TEMPLATE}" > "${tmp_service}"
  sudo install -m 0644 "${tmp_service}" "${SYSTEMD_TARGET}"
  sudo systemctl daemon-reload
  sudo systemctl enable --now vps-proxy-stack.service
  echo "Systemd service installed and enabled: vps-proxy-stack.service"
fi

if [[ "${INSTALL_CRON:-1}" == "1" ]]; then
  CRON_SCHEDULE="${BLACKLIST_CRON_SCHEDULE:-0 */6 * * *}"
  CRON_CMD="cd ${PROJECT_DIR} && /usr/bin/docker compose run --rm --no-deps mitmproxy bash cron/update_blacklist.sh >> ${PROJECT_DIR}/logs/blacklist-cron.log 2>&1"

  current_cron="$(crontab -l 2>/dev/null || true)"
  filtered_cron="$(printf '%s\n' "${current_cron}" | grep -v "${CRON_TAG}" || true)"
  {
    printf '%s\n' "${filtered_cron}"
    printf '%s %s %s\n' "${CRON_SCHEDULE}" "${CRON_CMD}" "${CRON_TAG}"
  } | crontab -

  echo "Blacklist cron schedule updated: ${CRON_SCHEDULE}"
fi

echo "Bootstrap completed."

# ---------------------------------------------------------------------------
# Health check — verify critical services came up
# ---------------------------------------------------------------------------
health_check() {
  local ok=0
  local fail=0

  echo ""
  echo "=== Post-start health check ==="
  sleep 5  # allow containers time to initialize

  # mitmproxy TCP reachability
  local proxy_port="${MITMPROXY_BIND_PORT:-8080}"
  if timeout 3 bash -c ">/dev/tcp/127.0.0.1/${proxy_port}" 2>/dev/null; then
    echo "[OK]   mitmproxy reachable on :${proxy_port}"
    ok=$((ok + 1))
  else
    echo "[FAIL] mitmproxy not reachable on :${proxy_port}"
    fail=$((fail + 1))
  fi

  # Unbound DNS resolution
  if docker compose -f "${PROJECT_DIR}/docker-compose.yml" \
      exec -T unbound nslookup example.com 127.0.0.1 >/dev/null 2>&1; then
    echo "[OK]   Unbound DNS resolving"
    ok=$((ok + 1))
  else
    echo "[WARN] Unbound DNS check failed — container may still be initializing"
  fi

  # Tor bootstrap progress
  local tor_log
  tor_log=$(docker compose -f "${PROJECT_DIR}/docker-compose.yml" \
    logs tor 2>/dev/null | tail -20 || true)
  if echo "${tor_log}" | grep -q "Bootstrapped 100%"; then
    echo "[OK]   Tor bootstrapped to 100%"
    ok=$((ok + 1))
  elif echo "${tor_log}" | grep -q "Bootstrapped"; then
    echo "[INFO] Tor bootstrap in progress (will complete in ~30 s)"
  else
    echo "[WARN] No Tor bootstrap log found — check: make logs"
  fi

  echo ""
  echo "Health check complete: ${ok} OK, ${fail} FAIL"
  if [[ "${fail}" -gt 0 ]]; then
    echo "       Run 'make logs' to investigate failures."
  fi
}

health_check
