#!/usr/bin/env bash
# ===========================================================================
#  generate-certs.sh - Generate TLS certificates for Unbound DoT
# ===========================================================================
#  Supports 3 modes (TLS_MODE in .env):
#
#    selfsigned   → generates self-signed .key + .crt in ./ssl-certificates/
#    letsencrypt  → certbot standalone (requires domain + open port 80)
#    cloudpanel   → uses certificates already generated by CloudPanel/Nginx
#
#  Usage: bash init/generate-certs.sh
# ===========================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  set -a; source "${ENV_FILE}"; set +a
fi

TLS_MODE="${TLS_MODE:-selfsigned}"
MY_DOMAIN="${MY_DOMAIN:-}"
MY_EMAIL="${MY_EMAIL:-}"
SSL_DIR="${PROJECT_DIR}/ssl-certificates"
CERT_DAYS="${TLS_CERT_DAYS:-365}"

# Output paths (default for selfsigned / letsencrypt)
KEY_FILE="${SSL_DIR}/server.key"
CRT_FILE="${SSL_DIR}/server.crt"

mkdir -p "${SSL_DIR}"

# ---------------------------------------------------------------------------
case "${TLS_MODE}" in

  # =========================================================================
  # SELF-SIGNED: no domain required, works immediately
  # =========================================================================
  selfsigned)
    if [[ -f "${KEY_FILE}" && -f "${CRT_FILE}" ]]; then
      echo "[✓] Self-signed certificates already present in ${SSL_DIR}/"
      # Check expiration
      if openssl x509 -checkend 604800 -noout -in "${CRT_FILE}" 2>/dev/null; then
        echo "    Expiration OK (> 7 days)."
      else
        echo "[!] Certificate is expiring or expired. Regenerating..."
        rm -f "${KEY_FILE}" "${CRT_FILE}"
      fi
    fi

    if [[ ! -f "${KEY_FILE}" ]]; then
      echo "[*] Generating self-signed certificate (${CERT_DAYS} days)..."

      # CN = configured domain, fallback to hostname
      CN="${MY_DOMAIN:-$(hostname -f 2>/dev/null || echo 'vps-proxy')}"

      # SAN: include IP, hostname, and domain (if provided)
      SAN="DNS:${CN},DNS:localhost,IP:127.0.0.1"
      if [[ -n "${MY_DOMAIN}" ]]; then
        SAN="${SAN},DNS:*.${MY_DOMAIN}"
      fi
      # Attempt to add public IPv4
      PUBLIC_IP="$(curl -4 -s --max-time 5 https://ifconfig.me || true)"
      if [[ -n "${PUBLIC_IP}" ]]; then
        SAN="${SAN},IP:${PUBLIC_IP}"
      fi

      openssl req -x509 -newkey rsa:4096 -sha256 \
        -days "${CERT_DAYS}" -nodes \
        -keyout "${KEY_FILE}" \
        -out "${CRT_FILE}" \
        -subj "/CN=${CN}" \
        -addext "subjectAltName=${SAN}" \
        2>/dev/null

      chmod 600 "${KEY_FILE}"
      chmod 644 "${CRT_FILE}"
      echo "[✓] Self-signed certificate generated:"
      echo "    Key: ${KEY_FILE}"
      echo "    Crt: ${CRT_FILE}"
      echo "    CN:  ${CN}"
      echo "    SAN: ${SAN}"
    fi

    # Export paths for unbound
    export TLS_SERVICE_KEY="/etc/nginx/ssl-certificates/server.key"
    export TLS_SERVICE_PEM="/etc/nginx/ssl-certificates/server.crt"
    ;;

  # =========================================================================
  # LET'S ENCRYPT: requires domain, email, open port 80
  # =========================================================================
  letsencrypt)
    if [[ -z "${MY_DOMAIN}" ]]; then
      echo "Error: TLS_MODE=letsencrypt requires MY_DOMAIN in .env"
      exit 1
    fi
    if [[ -z "${MY_EMAIL}" ]]; then
      echo "Error: TLS_MODE=letsencrypt requires MY_EMAIL in .env"
      exit 1
    fi

    LE_DIR="/etc/letsencrypt/live/${MY_DOMAIN}"
    KEY_FILE="${LE_DIR}/privkey.pem"
    CRT_FILE="${LE_DIR}/fullchain.pem"

    if [[ -f "${KEY_FILE}" && -f "${CRT_FILE}" ]]; then
      echo "[✓] Let's Encrypt certificates already available for ${MY_DOMAIN}"
      # Renew if needed
      if command -v certbot &>/dev/null; then
        certbot renew --quiet || true
      fi
    else
      echo "[*] Requesting Let's Encrypt certificate for ${MY_DOMAIN}..."

      # Install certbot if missing
      if ! command -v certbot &>/dev/null; then
        echo "[*] Installing certbot..."
        apt-get update && apt-get install -y --no-install-recommends certbot
      fi

      # Requires port 80 availability
      echo "[!] Certbot requires port 80 to be free (standalone mode)."
      certbot certonly --standalone \
        -d "${MY_DOMAIN}" \
        --email "${MY_EMAIL}" \
        --agree-tos --non-interactive \
        --preferred-challenges http

      echo "[✓] Let's Encrypt certificate issued for ${MY_DOMAIN}"
    fi

    # Copy to ssl-certificates/ for Docker mount
    cp -L "${KEY_FILE}" "${SSL_DIR}/server.key"
    cp -L "${CRT_FILE}" "${SSL_DIR}/server.crt"
    chmod 600 "${SSL_DIR}/server.key"
    chmod 644 "${SSL_DIR}/server.crt"

    # Cron for automatic renewal
    RENEW_SCRIPT="/usr/local/bin/renew-proxy-certs.sh"
    cat > "${RENEW_SCRIPT}" <<RENEW
#!/usr/bin/env bash
certbot renew --quiet
cp -L "${KEY_FILE}" "${SSL_DIR}/server.key"
cp -L "${CRT_FILE}" "${SSL_DIR}/server.crt"
cd "${PROJECT_DIR}" && docker compose restart unbound
RENEW
    chmod +x "${RENEW_SCRIPT}"
    # Add cron entry if missing
    CRON_TAG="# VPS_CERT_RENEW"
    current_cron="$(crontab -l 2>/dev/null || true)"
    if ! grep -q "${CRON_TAG}" <<< "${current_cron}"; then
      { echo "${current_cron}"; echo "0 4 * * * ${RENEW_SCRIPT} ${CRON_TAG}"; } | crontab -
      echo "[✓] Certificate renewal cron installed (daily at 04:00)."
    fi

    export TLS_SERVICE_KEY="/etc/nginx/ssl-certificates/server.key"
    export TLS_SERVICE_PEM="/etc/nginx/ssl-certificates/server.crt"
    ;;

  # =========================================================================
  # CLOUDPANEL: use certificates generated by CloudPanel for the domain
  # =========================================================================
  cloudpanel)
    if [[ -z "${MY_DOMAIN}" ]]; then
      echo "Error: TLS_MODE=cloudpanel requires MY_DOMAIN in .env"
      exit 1
    fi

    # Standard CloudPanel / Nginx paths
    CLP_KEY="/etc/nginx/ssl-certificates/${MY_DOMAIN}.key"
    CLP_CRT="/etc/nginx/ssl-certificates/${MY_DOMAIN}.crt"

    if [[ -f "${CLP_KEY}" && -f "${CLP_CRT}" ]]; then
      echo "[✓] CloudPanel certificates found for ${MY_DOMAIN}"
      # Copy to ssl-certificates/ for Docker mount
      cp -L "${CLP_KEY}" "${SSL_DIR}/server.key"
      cp -L "${CLP_CRT}" "${SSL_DIR}/server.crt"
      chmod 600 "${SSL_DIR}/server.key"
      chmod 644 "${SSL_DIR}/server.crt"
    else
      echo "[!] CloudPanel certificates not found:"
      echo "    Expected: ${CLP_KEY}"
      echo "             ${CLP_CRT}"
      echo ""
      echo "    Make sure to:"
      echo "    1. Access CloudPanel (https://<IP>:8443)"
      echo "    2. Add site '${MY_DOMAIN}'"
      echo "    3. Enable SSL (Let's Encrypt) in the panel"
      echo "    4. Re-run: bash init/generate-certs.sh"
      echo ""
      echo "[→] Generating temporary self-signed certificates as fallback..."
      export TLS_MODE=selfsigned
      exec bash "${BASH_SOURCE[0]}"
    fi

    # Cron to sync certificates from CloudPanel directory
    SYNC_SCRIPT="/usr/local/bin/sync-cloudpanel-certs.sh"
    cat > "${SYNC_SCRIPT}" <<SYNC
#!/usr/bin/env bash
cp -L "${CLP_KEY}" "${SSL_DIR}/server.key"
cp -L "${CLP_CRT}" "${SSL_DIR}/server.crt"
cd "${PROJECT_DIR}" && docker compose restart unbound
SYNC
    chmod +x "${SYNC_SCRIPT}"
    CRON_TAG="# VPS_CLP_CERT_SYNC"
    current_cron="$(crontab -l 2>/dev/null || true)"
    if ! grep -q "${CRON_TAG}" <<< "${current_cron}"; then
      { echo "${current_cron}"; echo "0 5 * * * ${SYNC_SCRIPT} ${CRON_TAG}"; } | crontab -
      echo "[✓] CloudPanel certificate sync cron installed (daily at 05:00)."
    fi

    export TLS_SERVICE_KEY="/etc/nginx/ssl-certificates/server.key"
    export TLS_SERVICE_PEM="/etc/nginx/ssl-certificates/server.crt"
    ;;

  *)
    echo "Error: invalid TLS_MODE='${TLS_MODE}'. Use: selfsigned | letsencrypt | cloudpanel"
    exit 1
    ;;
esac

echo ""
  echo "[*] TLS_MODE=${TLS_MODE} - certificates ready in ${SSL_DIR}/"
